version: '3.7'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        working_dir: /db
        volumes:
            - type: bind
              source: ./app/db
              target: /db

    nodejs:
        image: node:20-alpine
        container_name: nodejs_container
        ports:
            - '3000:3000'
        working_dir: /app
        volumes:
            - type: bind
              source: ./app
              target: /app
        depends_on:
            - postgres
        command: sh -c "npm install && npm run dev"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@i.ua
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - postgres
